//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopoData.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TopoData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alarm File Prefix 的本地化字符串。
        /// </summary>
        internal static string AlmFilePrefix {
            get {
                return ResourceManager.GetString("AlmFilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute 的本地化字符串。
        /// </summary>
        internal static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audit File Prefix 的本地化字符串。
        /// </summary>
        internal static string AuditFilePrefix {
            get {
                return ResourceManager.GetString("AuditFilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 batch number 的本地化字符串。
        /// </summary>
        internal static string batch {
            get {
                return ResourceManager.GetString("batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoolTrigTag 的本地化字符串。
        /// </summary>
        internal static string BoolTrigTag {
            get {
                return ResourceManager.GetString("BoolTrigTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 byTime 的本地化字符串。
        /// </summary>
        internal static string byTime {
            get {
                return ResourceManager.GetString("byTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 byWO 的本地化字符串。
        /// </summary>
        internal static string byWO {
            get {
                return ResourceManager.GetString("byWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CannelCfg 的本地化字符串。
        /// </summary>
        internal static string CannelCfg {
            get {
                return ResourceManager.GetString("CannelCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CannelName 的本地化字符串。
        /// </summary>
        internal static string CannelName {
            get {
                return ResourceManager.GetString("CannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CannelType 的本地化字符串。
        /// </summary>
        internal static string CannelType {
            get {
                return ResourceManager.GetString("CannelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want Exit this Application? 的本地化字符串。
        /// </summary>
        internal static string CfgExitApp {
            get {
                return ResourceManager.GetString("CfgExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want Exit this Application? Select [No] will change to Tral Mode. 的本地化字符串。
        /// </summary>
        internal static string CfgExitAppYN {
            get {
                return ResourceManager.GetString("CfgExitAppYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Configuration 的本地化字符串。
        /// </summary>
        internal static string cfgTitle {
            get {
                return ResourceManager.GetString("cfgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CollectionConsecutive  的本地化字符串。
        /// </summary>
        internal static string CollectionConsecutive {
            get {
                return ResourceManager.GetString("CollectionConsecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AcquisitionRisingEdge  的本地化字符串。
        /// </summary>
        internal static string CollectionRisingEdge {
            get {
                return ResourceManager.GetString("CollectionRisingEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company 的本地化字符串。
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comunication 的本地化字符串。
        /// </summary>
        internal static string Comunication {
            get {
                return ResourceManager.GetString("Comunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration 的本地化字符串。
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConfigSys 的本地化字符串。
        /// </summary>
        internal static string ConfigSys {
            get {
                return ResourceManager.GetString("ConfigSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 currentValue 的本地化字符串。
        /// </summary>
        internal static string currentValue {
            get {
                return ResourceManager.GetString("currentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Base 的本地化字符串。
        /// </summary>
        internal static string DataBase {
            get {
                return ResourceManager.GetString("DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataTable 的本地化字符串。
        /// </summary>
        internal static string DataTable {
            get {
                return ResourceManager.GetString("DataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataType 的本地化字符串。
        /// </summary>
        internal static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DB 的本地化字符串。
        /// </summary>
        internal static string DB {
            get {
                return ResourceManager.GetString("DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DBCfg 的本地化字符串。
        /// </summary>
        internal static string DBCfg {
            get {
                return ResourceManager.GetString("DBCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DBCreate 的本地化字符串。
        /// </summary>
        internal static string DBCreate {
            get {
                return ResourceManager.GetString("DBCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DB DataSource 的本地化字符串。
        /// </summary>
        internal static string DbDataSource {
            get {
                return ResourceManager.GetString("DbDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DBFile 的本地化字符串。
        /// </summary>
        internal static string DBFile {
            get {
                return ResourceManager.GetString("DBFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DBLocation 的本地化字符串。
        /// </summary>
        internal static string DBLocation {
            get {
                return ResourceManager.GetString("DBLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DB Store Duration 的本地化字符串。
        /// </summary>
        internal static string DbStoreDuration {
            get {
                return ResourceManager.GetString("DbStoreDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DB Store Time 的本地化字符串。
        /// </summary>
        internal static string DBStoreTime {
            get {
                return ResourceManager.GetString("DBStoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DBTable 的本地化字符串。
        /// </summary>
        internal static string DBTable {
            get {
                return ResourceManager.GetString("DBTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DBTest 的本地化字符串。
        /// </summary>
        internal static string DBTest {
            get {
                return ResourceManager.GetString("DBTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database created and connection good. 的本地化字符串。
        /// </summary>
        internal static string DbTestOk {
            get {
                return ResourceManager.GetString("DbTestOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DBType 的本地化字符串。
        /// </summary>
        internal static string DBType {
            get {
                return ResourceManager.GetString("DBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeleteDBDate 的本地化字符串。
        /// </summary>
        internal static string DeleteDBDate {
            get {
                return ResourceManager.GetString("DeleteDBDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeletFail 的本地化字符串。
        /// </summary>
        internal static string DeletFail {
            get {
                return ResourceManager.GetString("DeletFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeletSucess 的本地化字符串。
        /// </summary>
        internal static string DeletSucess {
            get {
                return ResourceManager.GetString("DeletSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 diaExpress 的本地化字符串。
        /// </summary>
        internal static string diaExpress {
            get {
                return ResourceManager.GetString("diaExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 diaExpressCheck 的本地化字符串。
        /// </summary>
        internal static string diaExpressCheck {
            get {
                return ResourceManager.GetString("diaExpressCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comunication Diagnosis 的本地化字符串。
        /// </summary>
        internal static string diaTitle {
            get {
                return ResourceManager.GetString("diaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Down 的本地化字符串。
        /// </summary>
        internal static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drive Free Percentage 的本地化字符串。
        /// </summary>
        internal static string DriveFreePercentage {
            get {
                return ResourceManager.GetString("DriveFreePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drive Free Space 的本地化字符串。
        /// </summary>
        internal static string DriveFreeSpace {
            get {
                return ResourceManager.GetString("DriveFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DriverType 的本地化字符串。
        /// </summary>
        internal static string DriverType {
            get {
                return ResourceManager.GetString("DriverType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drive Space 的本地化字符串。
        /// </summary>
        internal static string DriveSpace {
            get {
                return ResourceManager.GetString("DriveSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Log 的本地化字符串。
        /// </summary>
        internal static string EnableLog4 {
            get {
                return ResourceManager.GetString("EnableLog4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EquipmentCfguration 的本地化字符串。
        /// </summary>
        internal static string EquipmentCfguration {
            get {
                return ResourceManager.GetString("EquipmentCfguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EquipmentName 的本地化字符串。
        /// </summary>
        internal static string EquipmentName {
            get {
                return ResourceManager.GetString("EquipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipments 的本地化字符串。
        /// </summary>
        internal static string Equipments {
            get {
                return ResourceManager.GetString("Equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Time 的本地化字符串。
        /// </summary>
        internal static string eTime {
            get {
                return ResourceManager.GetString("eTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExportChart 的本地化字符串。
        /// </summary>
        internal static string ExportChart {
            get {
                return ResourceManager.GetString("ExportChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExportExcel 的本地化字符串。
        /// </summary>
        internal static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression 的本地化字符串。
        /// </summary>
        internal static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Upload 的本地化字符串。
        /// </summary>
        internal static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alarm 的本地化字符串。
        /// </summary>
        internal static string frmAlarm {
            get {
                return ResourceManager.GetString("frmAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AuditTrail 的本地化字符串。
        /// </summary>
        internal static string frmAuditTrail {
            get {
                return ResourceManager.GetString("frmAuditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CannelCfg 的本地化字符串。
        /// </summary>
        internal static string frmCannelCfg {
            get {
                return ResourceManager.GetString("frmCannelCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataSampleCfg 的本地化字符串。
        /// </summary>
        internal static string frmDataSampleCfg {
            get {
                return ResourceManager.GetString("frmDataSampleCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 frmDiagnose 的本地化字符串。
        /// </summary>
        internal static string frmDiagnose {
            get {
                return ResourceManager.GetString("frmDiagnose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExpressTagCfg 的本地化字符串。
        /// </summary>
        internal static string frmExpressTagCfg {
            get {
                return ResourceManager.GetString("frmExpressTagCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HistryQuery 的本地化字符串。
        /// </summary>
        internal static string frmHisQuery {
            get {
                return ResourceManager.GetString("frmHisQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkorderSelect 的本地化字符串。
        /// </summary>
        internal static string frmLSelect {
            get {
                return ResourceManager.GetString("frmLSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comunication 的本地化字符串。
        /// </summary>
        internal static string frmLTreeNavigate {
            get {
                return ResourceManager.GetString("frmLTreeNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StepSampleCfg 的本地化字符串。
        /// </summary>
        internal static string frmStepSampleCfg {
            get {
                return ResourceManager.GetString("frmStepSampleCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SystemCfg 的本地化字符串。
        /// </summary>
        internal static string frmSystemCfg {
            get {
                return ResourceManager.GetString("frmSystemCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetEndpoint 的本地化字符串。
        /// </summary>
        internal static string GetEndpoint {
            get {
                return ResourceManager.GetString("GetEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetTag 的本地化字符串。
        /// </summary>
        internal static string GetTag {
            get {
                return ResourceManager.GetString("GetTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetThisItem 的本地化字符串。
        /// </summary>
        internal static string GetThisItem {
            get {
                return ResourceManager.GetString("GetThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hour 的本地化字符串。
        /// </summary>
        internal static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LotNum 的本地化字符串。
        /// </summary>
        internal static string LotNum {
            get {
                return ResourceManager.GetString("LotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Austar-AuDAServer 的本地化字符串。
        /// </summary>
        internal static string mainTitle {
            get {
                return ResourceManager.GetString("mainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MenAbout 的本地化字符串。
        /// </summary>
        internal static string MenAbout {
            get {
                return ResourceManager.GetString("MenAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MenDataTable 的本地化字符串。
        /// </summary>
        internal static string MenChannel {
            get {
                return ResourceManager.GetString("MenChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MenDataTable 的本地化字符串。
        /// </summary>
        internal static string MenDataTable {
            get {
                return ResourceManager.GetString("MenDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MenDiagnose 的本地化字符串。
        /// </summary>
        internal static string MenDiagnose {
            get {
                return ResourceManager.GetString("MenDiagnose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MenFormula 的本地化字符串。
        /// </summary>
        internal static string MenFormula {
            get {
                return ResourceManager.GetString("MenFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MenHistory 的本地化字符串。
        /// </summary>
        internal static string MenHistory {
            get {
                return ResourceManager.GetString("MenHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MenSystem 的本地化字符串。
        /// </summary>
        internal static string MenSystem {
            get {
                return ResourceManager.GetString("MenSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MenuGetSubItems 的本地化字符串。
        /// </summary>
        internal static string MenuGetSubItems {
            get {
                return ResourceManager.GetString("MenuGetSubItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgAttributeError1 的本地化字符串。
        /// </summary>
        internal static string msgAttributeError1 {
            get {
                return ResourceManager.GetString("msgAttributeError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgChartExporFail 的本地化字符串。
        /// </summary>
        internal static string msgChartExporFail {
            get {
                return ResourceManager.GetString("msgChartExporFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgChartExportSucess 的本地化字符串。
        /// </summary>
        internal static string msgChartExportSucess {
            get {
                return ResourceManager.GetString("msgChartExportSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgCreateDBFail 的本地化字符串。
        /// </summary>
        internal static string msgCreateDBFail {
            get {
                return ResourceManager.GetString("msgCreateDBFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgDBcFail 的本地化字符串。
        /// </summary>
        internal static string msgDBcFail {
            get {
                return ResourceManager.GetString("msgDBcFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgDBcOK 的本地化字符串。
        /// </summary>
        internal static string msgDBcOK {
            get {
                return ResourceManager.GetString("msgDBcOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgDBCreateFail1 的本地化字符串。
        /// </summary>
        internal static string msgDBCreateFail1 {
            get {
                return ResourceManager.GetString("msgDBCreateFail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgDBCreateFail2 的本地化字符串。
        /// </summary>
        internal static string msgDBCreateFail2 {
            get {
                return ResourceManager.GetString("msgDBCreateFail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgDBCreateOK 的本地化字符串。
        /// </summary>
        internal static string msgDBCreateOK {
            get {
                return ResourceManager.GetString("msgDBCreateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgDBQuering 的本地化字符串。
        /// </summary>
        internal static string msgDBQuering {
            get {
                return ResourceManager.GetString("msgDBQuering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgDBSyncOK 的本地化字符串。
        /// </summary>
        internal static string msgDBSyncOK {
            get {
                return ResourceManager.GetString("msgDBSyncOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgDBTbcFail 的本地化字符串。
        /// </summary>
        internal static string msgDBTbcFail {
            get {
                return ResourceManager.GetString("msgDBTbcFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgDBTitleNotNull 的本地化字符串。
        /// </summary>
        internal static string msgDBTitleNotNull {
            get {
                return ResourceManager.GetString("msgDBTitleNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgDbTskNameNotNull 的本地化字符串。
        /// </summary>
        internal static string msgDbTskNameNotNull {
            get {
                return ResourceManager.GetString("msgDbTskNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgExample1 的本地化字符串。
        /// </summary>
        internal static string msgExample1 {
            get {
                return ResourceManager.GetString("msgExample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgExample2 的本地化字符串。
        /// </summary>
        internal static string msgExample2 {
            get {
                return ResourceManager.GetString("msgExample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgExport1 的本地化字符串。
        /// </summary>
        internal static string msgExport1 {
            get {
                return ResourceManager.GetString("msgExport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgExport2 的本地化字符串。
        /// </summary>
        internal static string msgExport2 {
            get {
                return ResourceManager.GetString("msgExport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgExportExcelFail 的本地化字符串。
        /// </summary>
        internal static string msgExportExcelFail {
            get {
                return ResourceManager.GetString("msgExportExcelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgImportExcelFail 的本地化字符串。
        /// </summary>
        internal static string msgImportExcelFail {
            get {
                return ResourceManager.GetString("msgImportExcelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgImportTag1 的本地化字符串。
        /// </summary>
        internal static string msgImportTag1 {
            get {
                return ResourceManager.GetString("msgImportTag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgIPWrong 的本地化字符串。
        /// </summary>
        internal static string msgIPWrong {
            get {
                return ResourceManager.GetString("msgIPWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgNoMatchQFail 的本地化字符串。
        /// </summary>
        internal static string msgNoMatchQFail {
            get {
                return ResourceManager.GetString("msgNoMatchQFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgNoTableQFail 的本地化字符串。
        /// </summary>
        internal static string msgNoTableQFail {
            get {
                return ResourceManager.GetString("msgNoTableQFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgNoTagFail 的本地化字符串。
        /// </summary>
        internal static string msgNoTagFail {
            get {
                return ResourceManager.GetString("msgNoTagFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgRptExportFail 的本地化字符串。
        /// </summary>
        internal static string msgRptExportFail {
            get {
                return ResourceManager.GetString("msgRptExportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgRptExportSucess 的本地化字符串。
        /// </summary>
        internal static string msgRptExportSucess {
            get {
                return ResourceManager.GetString("msgRptExportSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgRptQuerySucess 的本地化字符串。
        /// </summary>
        internal static string msgRptQuerySucess {
            get {
                return ResourceManager.GetString("msgRptQuerySucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgRSError 的本地化字符串。
        /// </summary>
        internal static string msgRSError {
            get {
                return ResourceManager.GetString("msgRSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgSampleWindowError1 的本地化字符串。
        /// </summary>
        internal static string msgSampleWindowError1 {
            get {
                return ResourceManager.GetString("msgSampleWindowError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgSaveError 的本地化字符串。
        /// </summary>
        internal static string msgSaveError {
            get {
                return ResourceManager.GetString("msgSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgSctStore 的本地化字符串。
        /// </summary>
        internal static string msgSctStore {
            get {
                return ResourceManager.GetString("msgSctStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgSelectEndpoint 的本地化字符串。
        /// </summary>
        internal static string msgSelectEndpoint {
            get {
                return ResourceManager.GetString("msgSelectEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgSelectLine 的本地化字符串。
        /// </summary>
        internal static string msgSelectLine {
            get {
                return ResourceManager.GetString("msgSelectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgStartsWithSpecialCharOrDigitError 的本地化字符串。
        /// </summary>
        internal static string msgStartsWithSpecialCharOrDigitError {
            get {
                return ResourceManager.GetString("msgStartsWithSpecialCharOrDigitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgTag1 的本地化字符串。
        /// </summary>
        internal static string msgTag1 {
            get {
                return ResourceManager.GetString("msgTag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgTag2 的本地化字符串。
        /// </summary>
        internal static string msgTag2 {
            get {
                return ResourceManager.GetString("msgTag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgTag3 的本地化字符串。
        /// </summary>
        internal static string msgTag3 {
            get {
                return ResourceManager.GetString("msgTag3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgTagNameNotNull 的本地化字符串。
        /// </summary>
        internal static string msgTagNameNotNull {
            get {
                return ResourceManager.GetString("msgTagNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgTagNameSelectNotExist 的本地化字符串。
        /// </summary>
        internal static string msgTagNameSelectNotExist {
            get {
                return ResourceManager.GetString("msgTagNameSelectNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgUACfgError1 的本地化字符串。
        /// </summary>
        internal static string msgUACfgError1 {
            get {
                return ResourceManager.GetString("msgUACfgError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgWoNotNullFail 的本地化字符串。
        /// </summary>
        internal static string msgWoNotNullFail {
            get {
                return ResourceManager.GetString("msgWoNotNullFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 msgWoTagTypeError 的本地化字符串。
        /// </summary>
        internal static string msgWoTagTypeError {
            get {
                return ResourceManager.GetString("msgWoTagTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No data, and cannot export report. 的本地化字符串。
        /// </summary>
        internal static string NoDataReport {
            get {
                return ResourceManager.GetString("NoDataReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Num 的本地化字符串。
        /// </summary>
        internal static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoadAlarmFile 的本地化字符串。
        /// </summary>
        internal static string OpenAlm {
            get {
                return ResourceManager.GetString("OpenAlm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phase 的本地化字符串。
        /// </summary>
        internal static string Phase {
            get {
                return ResourceManager.GetString("Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PLC_Cfg_Notes 的本地化字符串。
        /// </summary>
        internal static string PLC_Cfg_Notes {
            get {
                return ResourceManager.GetString("PLC_Cfg_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 port 的本地化字符串。
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product 的本地化字符串。
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PromptComTest 的本地化字符串。
        /// </summary>
        internal static string PromptComTest {
            get {
                return ResourceManager.GetString("PromptComTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt Message 的本地化字符串。
        /// </summary>
        internal static string PromptMessage {
            get {
                return ResourceManager.GetString("PromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QstDeletAll 的本地化字符串。
        /// </summary>
        internal static string QstDeletAll {
            get {
                return ResourceManager.GetString("QstDeletAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QstDeletDBColumn 的本地化字符串。
        /// </summary>
        internal static string QstDeletDBColumn {
            get {
                return ResourceManager.GetString("QstDeletDBColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QstDeletSelected 的本地化字符串。
        /// </summary>
        internal static string QstDeletSelected {
            get {
                return ResourceManager.GetString("QstDeletSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 的本地化字符串。
        /// </summary>
        internal static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RealTimeValue 的本地化字符串。
        /// </summary>
        internal static string RealTimeValue {
            get {
                return ResourceManager.GetString("RealTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recipe 的本地化字符串。
        /// </summary>
        internal static string Recipe {
            get {
                return ResourceManager.GetString("Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S7_400Look4Cfg 的本地化字符串。
        /// </summary>
        internal static string S7_400Look4Cfg {
            get {
                return ResourceManager.GetString("S7_400Look4Cfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save_Restart 的本地化字符串。
        /// </summary>
        internal static string Save_Restart {
            get {
                return ResourceManager.GetString("Save_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ServerNode 的本地化字符串。
        /// </summary>
        internal static string ServerNode {
            get {
                return ResourceManager.GetString("ServerNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service Started... ... 的本地化字符串。
        /// </summary>
        internal static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software Automatic Start 的本地化字符串。
        /// </summary>
        internal static string SftwareAutoStart {
            get {
                return ResourceManager.GetString("SftwareAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share Folder 的本地化字符串。
        /// </summary>
        internal static string ShareFolder {
            get {
                return ResourceManager.GetString("ShareFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software Automatic Start 的本地化字符串。
        /// </summary>
        internal static string SoftwareAutoStart {
            get {
                return ResourceManager.GetString("SoftwareAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software Tray Start 的本地化字符串。
        /// </summary>
        internal static string SoftwareTrayStart {
            get {
                return ResourceManager.GetString("SoftwareTrayStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StepName 的本地化字符串。
        /// </summary>
        internal static string StepName {
            get {
                return ResourceManager.GetString("StepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SteptType 的本地化字符串。
        /// </summary>
        internal static string SteptType {
            get {
                return ResourceManager.GetString("SteptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Time 的本地化字符串。
        /// </summary>
        internal static string sTime {
            get {
                return ResourceManager.GetString("sTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SynchronizeTable 的本地化字符串。
        /// </summary>
        internal static string SynchronizeTable {
            get {
                return ResourceManager.GetString("SynchronizeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TableColName 的本地化字符串。
        /// </summary>
        internal static string TableColName {
            get {
                return ResourceManager.GetString("TableColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TableName 的本地化字符串。
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TagComm 的本地化字符串。
        /// </summary>
        internal static string TagComm {
            get {
                return ResourceManager.GetString("TagComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag Count 的本地化字符串。
        /// </summary>
        internal static string TagCount {
            get {
                return ResourceManager.GetString("TagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TagDevice 的本地化字符串。
        /// </summary>
        internal static string TagDevice {
            get {
                return ResourceManager.GetString("TagDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal Tag 的本地化字符串。
        /// </summary>
        internal static string TagInternal {
            get {
                return ResourceManager.GetString("TagInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Internal tag list 的本地化字符串。
        /// </summary>
        internal static string TagInternalList {
            get {
                return ResourceManager.GetString("TagInternalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TagList 的本地化字符串。
        /// </summary>
        internal static string TagList {
            get {
                return ResourceManager.GetString("TagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TagName 的本地化字符串。
        /// </summary>
        internal static string TagName {
            get {
                return ResourceManager.GetString("TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TagWO 的本地化字符串。
        /// </summary>
        internal static string TagWO {
            get {
                return ResourceManager.GetString("TagWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Task 的本地化字符串。
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TaskList 的本地化字符串。
        /// </summary>
        internal static string TaskList {
            get {
                return ResourceManager.GetString("TaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Mode(Sample 1000ms) 的本地化字符串。
        /// </summary>
        internal static string testMode {
            get {
                return ResourceManager.GetString("testMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TimeEnd 的本地化字符串。
        /// </summary>
        internal static string TimeEnd {
            get {
                return ResourceManager.GetString("TimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Scale Table 的本地化字符串。
        /// </summary>
        internal static string TimeScaleTable {
            get {
                return ResourceManager.GetString("TimeScaleTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TimeScaleTableNotNullFail 的本地化字符串。
        /// </summary>
        internal static string TimeScaleTableNotNullFail {
            get {
                return ResourceManager.GetString("TimeScaleTableNotNullFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TimeStart 的本地化字符串。
        /// </summary>
        internal static string TimeStart {
            get {
                return ResourceManager.GetString("TimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TitleStep 的本地化字符串。
        /// </summary>
        internal static string TitleStep {
            get {
                return ResourceManager.GetString("TitleStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 toolStripConnFail 的本地化字符串。
        /// </summary>
        internal static string toolStripConnFail {
            get {
                return ResourceManager.GetString("toolStripConnFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 toolStripConnOK 的本地化字符串。
        /// </summary>
        internal static string toolStripConnOK {
            get {
                return ResourceManager.GetString("toolStripConnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 toolStripTryOut1 的本地化字符串。
        /// </summary>
        internal static string toolStripTryOut1 {
            get {
                return ResourceManager.GetString("toolStripTryOut1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 toolStripTryOut2 的本地化字符串。
        /// </summary>
        internal static string toolStripTryOut2 {
            get {
                return ResourceManager.GetString("toolStripTryOut2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 toolStripTryOut3 的本地化字符串。
        /// </summary>
        internal static string toolStripTryOut3 {
            get {
                return ResourceManager.GetString("toolStripTryOut3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 treeCannel 的本地化字符串。
        /// </summary>
        internal static string treeCannel {
            get {
                return ResourceManager.GetString("treeCannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 treeDiagnose 的本地化字符串。
        /// </summary>
        internal static string treeDiagnose {
            get {
                return ResourceManager.GetString("treeDiagnose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 treeHistoricalQuery 的本地化字符串。
        /// </summary>
        internal static string treeHistoricalQuery {
            get {
                return ResourceManager.GetString("treeHistoricalQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 treeStepStoreCfg 的本地化字符串。
        /// </summary>
        internal static string treeStepStoreCfg {
            get {
                return ResourceManager.GetString("treeStepStoreCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 treeStoreCfg 的本地化字符串。
        /// </summary>
        internal static string treeStoreCfg {
            get {
                return ResourceManager.GetString("treeStoreCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 treeSysCfg 的本地化字符串。
        /// </summary>
        internal static string treeSysCfg {
            get {
                return ResourceManager.GetString("treeSysCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TrendChart 的本地化字符串。
        /// </summary>
        internal static string TrendChart {
            get {
                return ResourceManager.GetString("TrendChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 triggering_condition 的本地化字符串。
        /// </summary>
        internal static string triggering_condition {
            get {
                return ResourceManager.GetString("triggering_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UOM 的本地化字符串。
        /// </summary>
        internal static string UOM {
            get {
                return ResourceManager.GetString("UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up 的本地化字符串。
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uppdate 的本地化字符串。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string User_psd {
            get {
                return ResourceManager.GetString("User_psd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User_user 的本地化字符串。
        /// </summary>
        internal static string User_user {
            get {
                return ResourceManager.GetString("User_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UseUserLogIn 的本地化字符串。
        /// </summary>
        internal static string UseUserLogIn {
            get {
                return ResourceManager.GetString("UseUserLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ValueDefault 的本地化字符串。
        /// </summary>
        internal static string ValueDefault {
            get {
                return ResourceManager.GetString("ValueDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebAPICfg 的本地化字符串。
        /// </summary>
        internal static string WebAPICfg {
            get {
                return ResourceManager.GetString("WebAPICfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 work order 的本地化字符串。
        /// </summary>
        internal static string wo {
            get {
                return ResourceManager.GetString("wo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WriteDown 的本地化字符串。
        /// </summary>
        internal static string WriteDown {
            get {
                return ResourceManager.GetString("WriteDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WriteOperation 的本地化字符串。
        /// </summary>
        internal static string WriteOperation {
            get {
                return ResourceManager.GetString("WriteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
